### ISSUE TITLE
Kubernetes example

### ISSUE THREAD

**Issue by vakaobr** [D3473R/jitsi-keycloak#4]
Hello there again! 

Used the following template to deploy it into a kubernetes cluster, maybe could be useful to help somebody.

I replaced my original values by `my-fabulous-`something, so, if somebody is looking to use it, could be useful to a locate for the values and replace it.

If the file its being deployed using any ci tool (in my case I'm using gitlab-ci), which I did was:

- Created "base" file, containing the values as variables (namespace, values for secrets, configmap, etc);
- During pipeline execution, did a `envsubst < mybasefile.yml > deployment.yml`;
- Deployed the `deployment.yml` to cluster;
- Profit! \o/

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitsi-keycloak
  namespace: my-fabulous-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jitsi-keycloak
  template:
    metadata:
      labels:
        app: my-fabulous-app
        run: jitsi-keycloak
    spec:
      containers:
        - name: jitsi-keycloak
          image: my-fabulous-docker-image
          ports:
          - containerPort: 3000
          resources:
            limits:
              memory: "256Mi"
              cpu: "150m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: keycloak-json
              mountPath: "/config"
              readOnly: true
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JITSI_SECRET
              valueFrom:
                  secretKeyRef:
                  name: jitsi-keycloak-secret
                  key: JITSI_SECRET
            - name: DEFAULT_ROOM
              valueFrom:
                configMapKeyRef:
                  name: jitsi-keycloak-config
                  key: DEFAULT_ROOM
            - name: INVITE_ROOM_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: jitsi-keycloak-config
                  key: INVITE_ROOM_PREFIX
            - name: JITSI_URL
              valueFrom:
                configMapKeyRef:
                  name: jitsi-keycloak-config
                  key: JITSI_URL
            - name: JITSI_SUB
              valueFrom:
                configMapKeyRef:
                  name: jitsi-keycloak-config
                  key: JITSI_SUB
      volumes:
        - name: keycloak-json
          secret:
            secretName: jitsi-keycloak-config-json
      imagePullSecrets:
      - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  name: jitsi-keycloak-service
  labels:
    app: my-fabulous-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 3000
  selector:
    run: jitsi-keycloak
---
apiVersion: v1
kind: Secret
metadata:
  name: jitsi-keycloak-config-json
  namespace: my-fabulous-namespace
  labels:
    app: jitsi-keycloak  
stringData:
  keycloak.json: |-
    {
      "realm": "my-fabulous-keycloak-realm",
      "auth-server-url": "my-fabulous-keycloak-auth-url",
      "ssl-required": "external",
      "resource": "my-fabulous-keycloak-client",
      "credentials": {
        "secret": "my-fabulous-keycloak-secret"
      },
      "confidential-port": 0
    }
type: Opaque   
---
apiVersion: v1
kind: Secret
metadata:
  name: jitsi-keycloak-secret
  namespace: my-fabulous-namespace
  labels:
    app: jitsi-keycloak  
data:
  JITSI_SECRET: my-fabulous-keycloak-secret
type: Opaque
---
apiVersion: v1
data:
  DEFAULT_ROOM: my-fabulous-room
  INVITE_ROOM_PREFIX: my-fabulous-room-invite
  JITSI_SECRET: my-fabulous-keycloak-secret
  JITSI_SUB: my-fabulous-keycloak-jitsi-url
  JITSI_URL: https://my-fabulous-keycloak-jitsi-url
kind: ConfigMap
metadata:
  name: jitsi-keycloak-config
  namespace: my-fabulous-namespace
```
