### ISSUE TITLE
"Open Jitsi" button does not respond.

### ISSUE THREAD

**Issue by pabpazjim** [d3473r/jitsi-keycloak#48]
I am trying to use jitsi-keycloak with the docker-compose setup.

This is all I have configured so far:

docker-compose.yml

```
...

  jitsi-keycloak:
    image: d3473r/jitsi-keycloak:latest
    restart: unless-stopped
    container_name: jitsi-keycloak
    environment:
      JITSI_SECRET: JWT_APP_SECRET value
      DEFAULT_ROOM: meeting
      JITSI_URL: https://jitsi-domain/
      JITSI_SUB: jitsi-domain
    volumes:
      - ${CONFIG}/jitsi-keycloak/config:/config
    expose:
      - "3000"
    # This allows me to connect jitsi-keycloak to my nginx
    networks:
      reverse-proxy:

...

```

.env

```
...

ENABLE_AUTH=1
AUTH_TYPE=jwt
JWT_APP_ID=jitsi
JWT_APP_SECRET= SECRET
JWT_ACCEPTED_ISSUERS=jitsi
JWT_ACCEPTED_AUDIENCES=jitsi
TOKEN_AUTH_URL=https://jitsi-keycloak-domain/{room}
```

I am able to access Jitsi, go inside a meeting and be asked to log in through keycloak. Once I log in, i get redirected to this page:

![image](https://user-images.githubusercontent.com/43904563/158372527-1a12c3e4-9e23-40f7-b483-20e54913b4b3.png)

but the "OPEN JITSI" button does not do anthing. I thought it could be a Javascript thing, but Javascript is enabled in my browser (Firefox, tested also with Chrome).
