### ISSUE TITLE
clientId missing

### ISSUE THREAD

**Issue by Talanor** [D3473R/jitsi-keycloak#6]
Hello,
might be related to #5 (as I might not be using this project the proper way).

When I go to `http://<MYIP>:3000/`
I get this error in the console: `uncaught exception: clientId missing` and a blank page.
I have `clientId` in my `keycloak.json`, without further error message, I don't know where to investigate.

My docker-compose:
```
version: '3'

services:
    oidc:
        image: d3473r/jitsi-keycloak
        container_name: jisi-keycloak
        restart: unless-stopped
        environment:
            JITSI_SECRET: <SECRET>
            DEFAULT_ROOM: meeting
            INVITE_ROOM_PREFIX: invite
            JITSI_URL: https://<JITSI FQDN>/
            JITSI_SUB: <JITSI FQDN>
        networks:
            dbr0:
                ipv4_address: <MYIP>
            meet.jitsi:
        volumes:
            - ./oidc:/config
[...]
```

Thanks
