### ISSUE TITLE
Docker-compose invalid_client error

### ISSUE THREAD

**Issue by robertoyoc** [D3473R/jitsi-keycloak#7]
Can you please share your keycloak realm configuration?

I'm not able to get the secret in a public client (obvious reasons) so I changed it to a private client.

Selected client authenticator signed Jwt with client secret.

Visited `localhost:3000`, logged in, then Vue interface didn't load. 

On Safari console I got:

```
POST http://localhost:8080/auth/realms/Scientia/protocol/openid-connect/token
```

Response 400:
```
{
    "error": "invalid_client",
    "error_description": "Parameter client_assertion_type is missing"
}
```

My keycloak config file inside `example/config/` folder:

```

{
  "realm": "Scientia",
  "auth-server-url": "http://localhost:8080/auth/",
  "ssl-required": "external",
  "resource": "jitsi",
  "verify-token-audience": true,
  "credentials": {
    "secret-jwt": {
      "secret": "6e99879f-2cce-49a4-83da-9daec7473ba9"
    }
  },
  "use-resource-role-mappings": true,
  "confidential-port": 0,
  "policy-enforcer": {}
}
````

My docker compose file:
```
version: '3'

services:
  jitsi-keycloak:
    image: d3473r/jitsi-keycloak
    container_name: jisi-keycloak
    restart: unless-stopped
    environment:
      JITSI_SECRET: 6e99879f-2cce-49a4-83da-9daec7473ba9
      DEFAULT_ROOM: meeting
      INVITE_ROOM_PREFIX: invite
      JITSI_URL: https://localhost:32010/
      JITSI_SUB: sscs.works
    volumes:
    - ./config:/config
    ports:
    - 3000:3000
    networks:
      jitsi-keycloak:

networks: 
  jitsi-keycloak:

```
